diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    type: "diff_drive_controller/DiffDriveController"
    # Wheel joint names (ensure these match your URDF)
    left_wheel_names: ["joint_BackWheel_L"]
    right_wheel_names: ["joint_BackWheel_R"]
    wheel_separation: 0.55
    wheel_radius: 0.17
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0
    # Odometry settings
    publish_rate: 50.0
    enable_odom_tf: false
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    # Command input settings
    use_stamped_vel: false
    cmd_vel_timeout: 0.5
    open_loop: false
    velocity_rolling_window_size: 2




