ekf_localization_node:
  ros__parameters:
    use_sim_time: true
    two_d_mode: true
    frequency: 30.0
    # Frame configuration
    map_frame: odom
    odom_frame: odom
    base_link_frame: base_link
    # Wheel odometry input from diff_drive_controller
    odom0: diff_drive_controller/odom
    odom0_config: [true,  true,  false,   false, false, false,   true,  false, false,   false, false, false,   false, false, false]
    odom0_queue_size: 10
    # IMU input
    imu0: imu
    imu0_config: [false, false, false,   true,  true,  true,   false, false, false,   true,  true,  true,   false, false, false]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    # Output configuration
    publish_tf: true
    print_diagnostics: true




