# Nav2 parameters for simulation
use_sim_time: true

# Global costmap parameters
global_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 2.0
    publish_frequency: 2.0
    width: 20.0
    height: 20.0
    resolution: 0.05
    rolling_window: true
    track_unknown_space: true
    robot_radius: 0.30
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: depth_points
      depth_points:
        topic: camera/depth/points
        data_type: PointCloud2
        marking: true
        clearing: true
        obstacle_max_range: 5.0
        raytrace_max_range: 5.0
        min_obstacle_height: 0.10
        max_obstacle_height: 1.5
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 1.0
      cost_scaling_factor: 3.0

# Local costmap parameters
local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 10.0
    width: 6.0
    height: 6.0
    resolution: 0.05
    rolling_window: true
    robot_radius: 0.30
    plugins: ["voxel_layer", "inflation_layer"]
    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: True
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 16
      max_obstacle_height: 2.0
      mark_threshold: 0
      observation_sources: depth_points
      depth_points:
        topic: camera/depth/points
        data_type: PointCloud2
        marking: true
        clearing: true
        obstacle_max_range: 3.0
        raytrace_max_range: 3.0
        min_obstacle_height: 0.10
        max_obstacle_height: 1.5
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
      cost_scaling_factor: 2.0

# Planner server parameters
planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["NavfnPlanner"]
    use_sim_time: true
    NavfnPlanner:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

# Controller server parameters
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.2

# Behavior server parameters
behavior_server:
  ros__parameters:
    use_sim_time: true
    global_costmap_topic: global_costmap/costmap_raw
    local_costmap_topic: local_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    local_footprint_topic: local_costmap/published_footprint
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
      acceleration_limit: 2.5
      deceleration_limit: -2.5
      minimum_speed: 0.10
    wait:
      plugin: "nav2_behaviors::Wait"

# BT Navigator parameters
bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_nav_to_pose_bt_xml: "package://nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "package://nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"




